/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CalculadoraController;
import Enum.EnumOperacao;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;

/**
 *
 * @author vinic
 */
public class Calculadora extends javax.swing.JFrame {
      private CalculadoraController calculadoraController;  
      private EnumOperacao ultimaOperacao;
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        calculadoraController = new CalculadoraController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        BTNLimpaTela = new javax.swing.JButton();
        btnPositivoNegativo = new javax.swing.JButton();
        BtnPorcentagem = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnAdd7 = new javax.swing.JButton();
        btnAdd8 = new javax.swing.JButton();
        btnAdd9 = new javax.swing.JButton();
        btnMultiplica = new javax.swing.JButton();
        btnAdd4 = new javax.swing.JButton();
        btnAdd5 = new javax.swing.JButton();
        btnAdd6 = new javax.swing.JButton();
        btnSubtrai = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        btnAdd2 = new javax.swing.JButton();
        btnAdd3 = new javax.swing.JButton();
        btnSoma = new javax.swing.JButton();
        btnAdd0 = new javax.swing.JButton();
        btnAddVirgula = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();
        Visor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridLayout(5, 7));

        BTNLimpaTela.setText("AC");
        BTNLimpaTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLimpaTelaActionPerformed(evt);
            }
        });
        jPanel2.add(BTNLimpaTela);

        btnPositivoNegativo.setText("+/-");
        jPanel2.add(btnPositivoNegativo);

        BtnPorcentagem.setText("%");
        jPanel2.add(BtnPorcentagem);

        btnDividir.setText("/");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        jPanel2.add(btnDividir);

        btnAdd7.setText("7");
        btnAdd7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd7ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd7);

        btnAdd8.setText("8");
        btnAdd8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd8ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd8);

        btnAdd9.setText("9");
        btnAdd9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd9ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd9);

        btnMultiplica.setText("*");
        btnMultiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicaActionPerformed(evt);
            }
        });
        jPanel2.add(btnMultiplica);

        btnAdd4.setText("4");
        btnAdd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd4);

        btnAdd5.setText("5");
        btnAdd5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd5ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd5);

        btnAdd6.setText("6");
        btnAdd6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd6ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd6);

        btnSubtrai.setText("-");
        btnSubtrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtraiActionPerformed(evt);
            }
        });
        jPanel2.add(btnSubtrai);

        btnAdd1.setText("1");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd1);

        btnAdd2.setText("2");
        btnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd2);

        btnAdd3.setText("3");
        btnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd3);

        btnSoma.setText("+");
        btnSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomaActionPerformed(evt);
            }
        });
        jPanel2.add(btnSoma);

        btnAdd0.setText("0");
        btnAdd0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd0ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd0);

        btnAddVirgula.setText(",");
        btnAddVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVirgulaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddVirgula);

        jButton19.setText("Não Clique em Mim!!");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton19);

        btnResultado.setText("=");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });
        jPanel2.add(btnResultado);

        Visor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Visor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Visor.setText("0,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Visor)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Visor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd7ActionPerformed
        Digita("7");
    }//GEN-LAST:event_btnAdd7ActionPerformed

    private void btnAdd8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd8ActionPerformed
        Digita("8");
    }//GEN-LAST:event_btnAdd8ActionPerformed

    private void btnAdd9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd9ActionPerformed
        Digita("9");
    }//GEN-LAST:event_btnAdd9ActionPerformed

    private void btnAdd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd4ActionPerformed
        Digita("4");
    }//GEN-LAST:event_btnAdd4ActionPerformed

    private void btnAdd5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd5ActionPerformed
        Digita("5");
    }//GEN-LAST:event_btnAdd5ActionPerformed

    private void btnAdd6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd6ActionPerformed
        Digita("6");
    }//GEN-LAST:event_btnAdd6ActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        Digita("1");
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd2ActionPerformed
        Digita("2");
    }//GEN-LAST:event_btnAdd2ActionPerformed

    private void btnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd3ActionPerformed
        Digita("3");
    }//GEN-LAST:event_btnAdd3ActionPerformed

    private void btnAdd0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd0ActionPerformed
        Digita("0");
    }//GEN-LAST:event_btnAdd0ActionPerformed

    private void btnAddVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVirgulaActionPerformed
        Digita(",");
    }//GEN-LAST:event_btnAddVirgulaActionPerformed

    private void BTNLimpaTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLimpaTelaActionPerformed
        Limpa();
        calculadoraController.zerar();
    }//GEN-LAST:event_BTNLimpaTelaActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void btnSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomaActionPerformed
        calculadoraController.RealizaOperacao(EnumOperacao.SOMA, StringToDouble(Visor.getText()));
        ultimaOperacao = EnumOperacao.SOMA;
        Limpa();
    }//GEN-LAST:event_btnSomaActionPerformed

    private void btnSubtraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtraiActionPerformed
        calculadoraController.RealizaOperacao(EnumOperacao.SUBTRACAO, StringToDouble(Visor.getText()));
        ultimaOperacao = EnumOperacao.SUBTRACAO;
        Limpa();
    }//GEN-LAST:event_btnSubtraiActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        
        calculadoraController.RealizaOperacao(EnumOperacao.DIVISAO, StringToDouble(Visor.getText()));
        ultimaOperacao = EnumOperacao.DIVISAO;
        Limpa();
        
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnMultiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicaActionPerformed
        Limpa();
        calculadoraController.RealizaOperacao(EnumOperacao.MULTIPLICACAO, StringToDouble(Visor.getText()));
    }//GEN-LAST:event_btnMultiplicaActionPerformed

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
        calculadoraController.RealizaOperacao(ultimaOperacao, StringToDouble(Visor.getText()));
        Visor.setText(DoubleToString(calculadoraController.getTotal()));
    }//GEN-LAST:event_btnResultadoActionPerformed
    private String DoubleToString(Double numero){
        if(numero!= null){
            DecimalFormat formato = new DecimalFormat("##,###,###,##0.00", new DecimalFormatSymbols(new Locale("pt", "BR")));
            formato.setParseBigDecimal(true);
            return formato.format(numero);
        }
        return "";
    }
    private Double StringToDouble(String numero){
        NumberFormat nf = NumberFormat.getInstance();
        double dv = 0.00;
        try {
            dv = nf.parse(numero).doubleValue();
        }
        catch(ParseException Ex){
        
        }
        return dv;
    }
    private void Digita(String caractere) {
        if (Visor.getText().equals("0,00")) {
            Visor.setText(caractere);
        } else {
            if (caractere.equals(",") && Visor.getText().contains(",")) {

            } else {
                Visor.setText(Visor.getText().concat(caractere));
            }
            
        }
    }
    
    private void Limpa(){
        Visor.setText("0,00");
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNLimpaTela;
    private javax.swing.JButton BtnPorcentagem;
    private javax.swing.JTextField Visor;
    private javax.swing.JButton btnAdd0;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnAdd3;
    private javax.swing.JButton btnAdd4;
    private javax.swing.JButton btnAdd5;
    private javax.swing.JButton btnAdd6;
    private javax.swing.JButton btnAdd7;
    private javax.swing.JButton btnAdd8;
    private javax.swing.JButton btnAdd9;
    private javax.swing.JButton btnAddVirgula;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnMultiplica;
    private javax.swing.JButton btnPositivoNegativo;
    private javax.swing.JButton btnResultado;
    private javax.swing.JButton btnSoma;
    private javax.swing.JButton btnSubtrai;
    private javax.swing.JButton jButton19;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
